export const  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const  USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";

// REGISTER
export const  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";